In [ ]:
%matplotlib inline

Note: This notebook is derived from http://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html This work is licensed using PyTorch licensing terms here: https://github.com/pytorch/pytorch/blob/master/LICENSE


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [1]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  8.5899e+09,  0.0000e+00],
        [ 8.5899e+09,  7.0065e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  8.5899e+09,  0.0000e+00]])


Construct a randomly initialized matrix:



In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.5542,  0.9045,  0.1923],
        [ 0.9870,  0.8448,  0.3903],
        [ 0.9514,  0.2826,  0.2311],
        [ 0.9094,  0.9633,  0.3064],
        [ 0.8709,  0.6799,  0.5283]])


Construct a matrix filled zeros and of dtype long:



In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


Construct a tensor directly from data:



In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


or create a tensor basing on existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 0.8004, -0.6244,  0.2049],
        [ 0.2412, -0.7004, -1.1548],
        [-0.4847, -0.6510, -1.6785],
        [-1.5051, -0.0301, -0.3071],
        [-0.3848,  0.5707,  0.9093]])


Get its size:



In [7]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.4950,  0.2545,  0.3431],
        [ 1.1354, -0.4825, -0.2281],
        [-0.3433,  0.1562, -1.1681],
        [-1.0994,  0.5131,  0.2289],
        [-0.2529,  0.5717,  1.4842]])


Addition: syntax 2



In [9]:
print(torch.add(x, y))

tensor([[ 1.4950,  0.2545,  0.3431],
        [ 1.1354, -0.4825, -0.2281],
        [-0.3433,  0.1562, -1.1681],
        [-1.0994,  0.5131,  0.2289],
        [-0.2529,  0.5717,  1.4842]])


Addition: providing an output tensor as argument



In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.4950,  0.2545,  0.3431],
        [ 1.1354, -0.4825, -0.2281],
        [-0.3433,  0.1562, -1.1681],
        [-1.0994,  0.5131,  0.2289],
        [-0.2529,  0.5717,  1.4842]])


Addition: in-place



In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.4950,  0.2545,  0.3431],
        [ 1.1354, -0.4825, -0.2281],
        [-0.3433,  0.1562, -1.1681],
        [-1.0994,  0.5131,  0.2289],
        [-0.2529,  0.5717,  1.4842]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [12]:
print(x[:, 1])

tensor([-0.6244, -0.7004, -0.6510, -0.0301,  0.5707])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([ 1.9021])
1.9020640850067139


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [15]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [16]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.



In [17]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[ 2.  2.  2.  2.  2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!